### ISSUE TITLE
Use Case Diagram

### ISSUE THREAD

**Issue by Raja108N** [SazamAmmy/Software-Engineering-Sprints--OrionEngine-Ensemble#4]

**Comment by shjoy11** [comment]
<img width="391" alt="Use case diagram" src="https://github.com/SazamAmmy/Software-Engineering-Sprints--OrionEngine-Ensemble/assets/158183077/f15c5a1e-2372-4c1b-b0ce-d81f6afdffea">

**Comment by Raja108N** [comment]
<img alt="image" src="https://github.com/SazamAmmy/Software-Engineering-Sprints--OrionEngine-Ensemble/assets/159127703/8e9c8a60-4004-4478-bb19-23b0abf24195">
