### ISSUE TITLE
Class Diagramss

### ISSUE THREAD

**Issue by SazamAmmy** [SazamAmmy/Software-Engineering-Sprints--OrionEngine-Ensemble#5]

**Comment by SazamAmmy** [comment]
Complete it please!

**Comment by Raja108N** [comment]
Error: Missing Admin Privileges set for the class diagram.

**Comment by SazamAmmy** [comment]
The same issue has been already created and and one of our developer is working on it.  Thanks  @Raja108N

Regards,
Sudip
