### ISSUE TITLE
Create User Persona

### ISSUE THREAD

**Issue by SazamAmmy** [SazamAmmy/Software-Engineering-Sprints--OrionEngine-Ensemble#9]

**Comment by shjoy11** [comment]
Persona 1: John Nick

Background: John is a 32-year-old policy maker working for the local government. They have a background in public administration and are responsible for developing policies that address demographic changes and social needs.

Goals:
•To access up-to-date population data to inform policy decisions.
•To understand demographic trends for better resource allocation.

Needs:
•Easy access to comprehensive population data.
•Ability to filter and analyze data based on specific criteria (age, location, etc.).



Persona 2: Andreea Khan

Background: Andreea is a 28-year-old researcher at a non-profit organization focused on urban development. They have a degree in urban planning and are involved in projects that aim to improve living conditions in densely populated areas.

Goals:
•To gather detailed population statistics for research purposes.
•To compare population data across different regions and time periods.

Needs:
•Access to a wide range of population data.
•Tools for visualizing and exporting data for further analysis.

**Comment by shjoy11** [comment]
Persona 1:
![John Nick Persona](https://github.com/SazamAmmy/Software-Engineering-Sprints--OrionEngine-Ensemble/assets/158183077/2bb6e071-9d6f-42d1-8b57-14aaf1af723c)


Persona 2:

![Andreea Khan Persona](https://github.com/SazamAmmy/Software-Engineering-Sprints--OrionEngine-Ensemble/assets/158183077/137803f5-69b1-4edd-9a31-b800c1370fb7)
